### ISSUE TITLE
Aren't actions tied to a specific Store?

### ISSUE THREAD

**Issue by mfirry** [kenwheeler/mcfly#53]
It's sort of weird... 
I have 2 `store`s and 2 different `actions` module.
Both `actions` contain
```
    switch(payload.actionType) {
      case 'SET':
        //do something
```
It now looks like when I trigger one action, the other also gets called.

**Comment by capescuba** [comment]
Actions are unique per the constant that defines them.  They are not
necessarily specific to a store.

Dave

**Comment by jcperez-ch** [comment]
@mfirry that is the expected behaviour.  That is why you subscribe both stores to an specific action.  If you want to force `store1` to do something with the payload before `store2` you can always use in `store2` the `waitFor()` promise.  If you want 2 different actions, then you should name them differently.

**Comment by mfirry** [comment]
Good to know.
